# Python part 1

## Python fundamentals

In [2]:
3 + 5 * 4

23

In [3]:
weight_kg = 60 # integer

### Types of data

In [4]:
weight_kg = 60.3 # floating point

In [5]:
patient_id = "001" # string

In [6]:
weight_lb = 2.2 * weight_kg

In [7]:
patient_id = "patient_" + patient_id

In [8]:
print(weight_kg)

60.3


In [9]:
print(patient_id)

patient_001


In [10]:
print(patient_id, "weight in kilograms:", weight_kg)

patient_001 weight in kilograms: 60.3


In [11]:
print(type(weight_kg))

<class 'float'>


In [12]:
print(type(patient_id))

<class 'str'>


In [13]:
x = 4 / 3
print(type(x))

<class 'float'>


### Python lists

In [14]:
odds = [1, 3, 5, 7]
print("odds are:", odds)

odds are: [1, 3, 5, 7]


In [15]:
# Accessing elements through indexing
print("first element:", odds[0])

first element: 1


In [16]:
print("last element:", odds[3])

last element: 7


In [17]:
names = ["Curie", "Darwing", "Turing"]
print(names)

['Curie', 'Darwing', 'Turing']


In [18]:
names[1] = "Darwin"
print(names)

['Curie', 'Darwin', 'Turing']


#### Careful with mutable data

In [19]:
salsa = ["peppers", "onions", "cilantro", "tomatoes"]
my_salsa = salsa

# Let's change my recipe
my_salsa[0] = "hot peppers"
print("my salsa:", my_salsa)
print("salsa", salsa)

my salsa: ['hot peppers', 'onions', 'cilantro', 'tomatoes']
salsa ['hot peppers', 'onions', 'cilantro', 'tomatoes']


In [20]:
my_salsa = list(salsa)
my_salsa[2] = "basil"
print("my salsa", my_salsa)
print("salsa", salsa)

my salsa ['hot peppers', 'onions', 'basil', 'tomatoes']
salsa ['hot peppers', 'onions', 'cilantro', 'tomatoes']


## Analysing patient data

In [21]:
import numpy

In [23]:
data = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=",")

In [24]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [25]:
print(type(data))

<class 'numpy.ndarray'>


In [26]:
print(data.dtype)

float64


In [27]:
print(data.shape)

(60, 40)


In [28]:
# Indexing an array
print("first element in data:", data[0, 0])

first element in data: 0.0


In [29]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [31]:
subset = data[:3, -4:]
print(subset)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


### Statistics

In [32]:
print(numpy.mean(data))

6.14875


In [33]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print("maximum", maxval)
print("minimum", minval)
print("std", stdval)

maximum 20.0
minimum 0.0
std 4.613833197118566


In [34]:
patient_0 = data[0, :]
print("maximum inflammation patient 0", numpy.max(patient_0))

maximum inflammation patient 0 18.0


In [35]:
# mean per day over all patients
print(numpy.mean(data, axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [36]:
print(numpy.mean(data, axis=0).shape)

(40,)


In [37]:
# average per patient over all days
print(numpy.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [38]:
print(numpy.mean(data, axis=1).shape)

(60,)


### Visualizing data