# Python part 1

## Python fundamentals

In [2]:
3 + 5 * 4

23

In [3]:
weight_kg = 60 # integer

### Types of data

In [4]:
weight_kg = 60.3 # floating point

In [5]:
patient_id = "001" # string

In [6]:
weight_lb = 2.2 * weight_kg

In [7]:
patient_id = "patient_" + patient_id

In [8]:
print(weight_kg)

60.3


In [9]:
print(patient_id)

patient_001


In [10]:
print(patient_id, "weight in kilograms:", weight_kg)

patient_001 weight in kilograms: 60.3


In [11]:
print(type(weight_kg))

<class 'float'>


In [12]:
print(type(patient_id))

<class 'str'>


In [13]:
x = 4 / 3
print(type(x))

<class 'float'>


### Python lists

In [14]:
odds = [1, 3, 5, 7]
print("odds are:", odds)

odds are: [1, 3, 5, 7]


In [15]:
# Accessing elements through indexing
print("first element:", odds[0])

first element: 1


In [16]:
print("last element:", odds[3])

last element: 7


In [17]:
names = ["Curie", "Darwing", "Turing"]
print(names)

['Curie', 'Darwing', 'Turing']


In [18]:
names[1] = "Darwin"
print(names)

['Curie', 'Darwin', 'Turing']


#### Careful with mutable data

In [19]:
salsa = ["peppers", "onions", "cilantro", "tomatoes"]
my_salsa = salsa

# Let's change my recipe
my_salsa[0] = "hot peppers"
print("my salsa:", my_salsa)
print("salsa", salsa)

my salsa: ['hot peppers', 'onions', 'cilantro', 'tomatoes']
salsa ['hot peppers', 'onions', 'cilantro', 'tomatoes']


In [20]:
my_salsa = list(salsa)
my_salsa[2] = "basil"
print("my salsa", my_salsa)
print("salsa", salsa)

my salsa ['hot peppers', 'onions', 'basil', 'tomatoes']
salsa ['hot peppers', 'onions', 'cilantro', 'tomatoes']


## Analysing patient data

In [21]:
import numpy

In [23]:
data = numpy.loadtxt(fname="data/inflammation-01.csv", delimiter=",")

In [24]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [25]:
print(type(data))

<class 'numpy.ndarray'>


In [26]:
print(data.dtype)

float64


In [27]:
print(data.shape)

(60, 40)


In [28]:
# Indexing an array
print("first element in data:", data[0, 0])

first element in data: 0.0


In [29]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [31]:
subset = data[:3, -4:]
print(subset)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


### Statistics