# Analysing data

## Numpy

We will analyse patient data using a library called `numpy`. We will first **import** the library, then **load** the data 

In [1]:
import numpy

In [4]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

We loaded the data but did nothing else. Let's assign to a variable and print it

In [5]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(data)
type(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


numpy.ndarray

Numpy has specialised functionssuch as `shape`

In [6]:
print(data.shape)

(60, 40)


`shape` indicates `data` has 60 rows and 40 columns. The **type** of `data` is an `array`. Can be accessed as lists by indexes

In [8]:
print('first value', data[0, 0])
print('last value', data[59, 39])
print('last value re', data[-1, -1])

first value 0.0
last value 0.0
last value re 0.0


In [9]:
# slice the first 4 rows and the first 10 columns
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [10]:
# save a subset of the data
small = data[:3, 36:]
print(small)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [ ]:
# let's try descriptive stats
