# Analysing data

## Numpy

We will analyse patient data using a library called `numpy`. We will first **import** the library, then **load** the data 

In [1]:
import numpy

In [4]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

We loaded the data but did nothing else. Let's assign to a variable and print it

In [5]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(data)
type(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


numpy.ndarray